main: tk.shanebee.skriptpaper.SkriptPaper
name: Skript-Paper
version: ${project.version}
author: ShaneBee
website: https://github.com/ShaneBeee/Skript-Paper
description: Add more Skript syntaxes using the PaperAPI
softdepend: [Skript]